name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
          
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color .github/workflows/*
          
      - name: Install
        run: make install

      - name: Lint
        run: make lint

      # Tests are not made yet.
      # - name: Test
      #   run: make test
